{
    "name": "Calculator",
    "version": "1.0.32",
    "icon": "fas fa-calculator",
    "category": "assistance",
    "author": "Psychokiller1888",
    "maintainers": [
        "maxbachmann",
        "Jierka"
    ],
    "desc": "Do some calculation with alice",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [],
    "pipRequirements": [],
    "conditions": {
        "lang": [
            "en",
            "de",
            "fr"
        ]
    }
}